service:
  name: dropbox-integration

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  state: dev
  region: eu-west-2
  profile: test

functions:
  webhook_challenge:
    handler: handler.webhook_challenge
    events:
      - http:
          method: get
          path: dropbox-webhook
          integration: lambda
