service:
  name: dropbox-integration

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  state: dev
  region: eu-west-2
  profile: test

functions:
  webhook-challenge:
    handler: handler.webhookChallenge
    events:
      - http:
          method: get
          path: dropbox-webhook
          integration: lambda

          request:
            parameters:
              querystrings:
                challenge: true

          response:
            template: $input.path('$.body')

  webhook-notify:
    handler: handler.webhookNotify
    events:
      - http:
          method: post
          path: dropbox-webhook
          integration: lambda
