service: icarus

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack # compiles and bundles together typescript code
  - serverless-finch   # deploys static web pages to S3

provider:
  name: aws
  runtime: nodejs6.10
  state: dev
  region: eu-west-2
  profile: test
  environment:
    SLACK_CLIENT_ID: ${env:SLACK_CLIENT_ID}
    SLACK_CLIENT_SECRET: ${env:SLACK_CLIENT_SECRET}

functions:
  slack-login:
    handler: src/main/handler.slackLogin
    events:
      - http:
          method: get
          path: slack-login

          request:
            parameters:
              querystrings:
                code: true
